export type Role = "ResearchTeam" | "GradPostDoc" | "Trainee" | "Alumni";

export const teamData = [
  {
    id: "1",
    name: "Armita Kharmandar",
    job_title: "Data Analyst",
    image: "/images/team/armita_kharmandar.jpg",
    role: "ResearchTeam" as Role,
    bio: `Armita Kharmandar recently graduated from the University of Victoria, BC, with a master’s degree in electrical and computer engineering with specialization of Machine Learning and Data Science. Armita joined the lab as a co-op student (data analyst) in summer 2024, and then continued her work in the lab post-graduation as a data analyst. Her current project involves working on an agent-based simulation study to examine the impact of different trajectories in the use of HIV pre-exposure prophylaxis to prevent HIV transmission, specifically among adolescent girls and young women in Eastern and Southern Africa.
    
    In her role, Armita focuses on fine-tuning the model by identifying complex patterns and relationships within the extensive datasets generated by the agent-based model. Her responsibilities include designing and implementing a systematic set of model checks and refining the model by addressing demographic heterogeneity, analyzing fixed parameters, and conducting model parameterization and calibration to ensure accurate predictions of HIV transmission and intervention outcomes. Her forensic approach to model analyses and model checks are critical to ensuring transparency, reproducibility, and internal validity of the complex model.
    
    During her master’s research in University of Victoria, she specialized in sentiment analysis, applying transfer learning and neural network models via the Keras API. Her background in model development, data mining, and pattern recognition equips her with the skills to utilize several AI-based models implementing different techniques of supervised, unsupervised, reinforcement learning and neural network, improve model accuracy and derive meaningful insights from complex datasets.

    Looking ahead, Armita aims to broaden her expertise in mathematical modeling and the application of machine learning in public health to tackle global health challenges, with a particular interest in predictive modeling for health outcomes and interventions.
    `,
    status: "Unpacking a large HIV transmission dynamic agent-based model and shaping it into clear documentation and a polished manuscript.",
    linkedin: "https://www.linkedin.com/in/armita-kharmandar-34a480264/",
    orcid: "https://orcid.org/0000-0002-XXXX-XXXX"
  },

  {
    id: "2",
    name: "Huiting Ma",
    job_title: "Senior Data Scientist: Analyst",
    image: "/images/team/huiting_ma.jpg",
    role: "ResearchTeam" as Role,
    bio: `Huiting completed her Master of Science in Statistics at the University of British Columbia. She then worked as a Research Analyst at the Institute of Clinical Evaluative Sciences in Ontario, Canada, where she analyzed large administrative databases to inform policy making. Her research interests focus on using epidemiological, mathematical and biostatistical methods for COVID-19 and HIV/STI research.
    
    Currently, she leads observational epidemiology studies (see research section) as part of the Transitions project in Kenya and Ukraine, conducts COVID-19 mathematical modeling studies among people experiencing homelessness in the City of Toronto within [Ku-gaa-gii-pimitizi-win study](https://maphealth.ca/ku-gaa-gii-pimitizi-win/), and collaborates on the tPAF and Mpox projects in Kenya. Her projects include statistical and mathematical modeling, empiric estimation, and bias adjustments to parameterize and calibrate HIV transmission models in Kenya, Canada, South Africa, Kenya, and Eswatini. Huiting has participated as a first author or co-author on over 30 team papers, with selected works including:
    
    - H Ma*, AK Chan, SD Baral, C Fahim, S Straus, B Sander, S Mishra (2023) [Which curve are we flattening? The disproportionate impact of COVID-19 among economically marginalized communities in Ontario, Canada, was unchanged from wild-type to omicron.](https://academic.oup.com/ofid/article/10/1/ofac690/6957411?login=false) Open Forum Infectious Diseases 10(1): ofac690.
    - H Ma, KC Yiu, SD Baral, C Fahim, G Moloney, D Darvin, D Landsman, AK Chan, S Straus, S Mishra (2022) [COVID-19 cases among facility-staff by neighbourhood of residence and social and structural determinants: An observational study.](https://pubmed.ncbi.nlm.nih.gov/35867901/) JMIR Public Health Surveil 8(10): e34927.
    - A Rao, H Ma*, G Moloney, JC Kwong, P Juni, B Sander, R Kustra, S Baral, S Mishra (2021). [A disproportionate epidemic: COVID-19 cases and deaths among essential workers in Toronto, Canada.](https://www.sciencedirect.com/science/article/pii/S1047279721002180?via%3Dihub) Ann Epidemiol 63: 63 – 67.
    - E Roberts, H Ma*, P Bhattacharjee, HK Musyoki, P Gichangi, L Avery, J Musimbi, J Tsang, S Kaosa, J Kioko, ML Becker, S Mishra (2020). [Low program access despite high burden of sexual, structural, and reproductive health vulnerabilities among young women who sell sex in Kenya.](https://bmcpublichealth.biomedcentral.com/articles/10.1186/s12889-020-08872-6) BMC Public Health 20.
    - H Ma, L Wang, P Gichangi, V Mochache, G Manguro, HK Musyoki, P Bhattacharjee, F Cholette, P Sandstrom, ML Becker, S Mishra (2020). [Venue-based HIV testing at sex work hotspots to reach adolescent girls and young women living with HIV: a cross-sectional study in Mombasa, Kenya.](https://journals.lww.com/jaids/Abstract/9000/Venue_based_HIV_testing_at_sex_work_hotspots_to.96194.aspx) J Acquir Immune Defic Syndr 84(5): 470-479.
    
    *Co-first Author
    `,
    orcid: "https://orcid.org/0000-0003-1910-5614",
    googleScholar: "https://scholar.google.com/citations?hl=en&view_op=list_works&gmla=AJsN-F5YM4fgpjjc1aXnkH-lJerBTok6keQ2W3vtchixUyfViDgjc2_wTjZxZK4jDba20fj8Ey7Erh3uGmH8pPhoLEVrIc1zRedelJxgbpZzxIN26fHIIkCWrESbTeQTQ6h_NIv2kHzT&user=JKfF9IcAAAAJ&scilu=&scisig=AMD79ooAAAAAXhyZfnR31OUO78eRgArfn6PI0ULSHBc2&gmla=AJsN-F41KfVXJUbH8T8JjyIY9D1l5g5srmF1f7xkOZdHeUAdBldalzRTICEsE0k5qXk9Yr3bQBF2auiP1Mqanl-wvKcn0nzM9aDjQZ_xqRSFyJ0SJjplpMw&sciund=17836935417757669064/"
  },

  {
    id: "3",
    name: "Linwei Wang",
    job_title: "Senior Research Data Scientist: Epidemiologist",
    image: "/images/team/linwei_wang.jpg",
    role: "ResearchTeam" as Role,
    bio: `Linwei is a Senior Research Data Scientist – Epidemiologist at the MAP Centre for Urban Health Solutions, St Michael’s Hospital, Unity Health Toronto. She holds a bachelor’s degree in Applied Biological Science and a Master of Science degree in Epidemiology. She has extensive experience in the field of infectious diseases, including quantitative epidemiological studies of HIV/AIDS and COVID-19, and mathematical modeling of HIV transmission. She is experienced in working with large health administrative databases, longitudinal cohort studies, disease surveillance data, and various survey data. Her recent work also includes health equity research in the context of COVID-19 and mechanistic explanatory modeling of COVID-19 transmission and mortality using causal inference and quantitative bias analysis methodologies. Her work also includes analyzing epidemic and behavioral data, both to generate fundamental epidemiological insights and to support model parameterization and calibration.
    
    Health equity research and causal inference methodology: 
    
    Linwei is leading several quantitative epidemiological studies to investigate the patterns and mechanisms of social and structural inequalities in COVID-19 mortality, leveraging provincial health administrative data in Ontario (in collaboration with ICES). The first phase of the project (published in CID 2023) employed competing for risk survival analyses and demonstrated that area-level social determinants of health are associated with COVID-19-related mortality even after accounting for demographic and clinical factors; and COVID-19 has reversed patterns of lower non-COVID-19 mortality among racially minoritized groups.

    The second phase of the project includes evaluating the mediating role of vaccination and inequalities in COVID-19 morality by area-level income and teasing apart mediators of the differential patterns of COVID-19 mortality across racialized communities over time. Leveraging the causal mediation analysis along with quantitative bias analysis (E-value approach), the study has found that social inequalities in COVID-19 mortality by area-level income persisted over time, and the vaccination gap accounted for more than half of inequalities in COVID-19 mortality during wave 4&5. The work is currently under review with AJE.

    Building upon these projects, she is currently investigating the role of herd immunity in COVID-19 diagnosis and death.

    Sexual network contact patterns and transmission modeling:

    Linwei led the work of developing a new approach to quantify HIV serosorting (mixing matrices by perceived HIV status) using the Engage study sexual behavioral survey data (AJE 2020). Using this new matrix of serosorting, she led the work of evaluating the influence of serosorting on the HIV transmission impact of pre-exposure prophylaxis using a dynamic compartmental transmission model of HIV (AIDS 2021). Her work showed that ignoring HIV serosorting leads to large underestimates of the population-level impact of HIV pre-exposure prophylaxis. Thus, capturing this feature of sexual networks can provide more robust model-based evidence to inform intervention decisions.

    Linwei has participated as a first author or co-author on these team papers:
    
    - Wang L, Swayze S, Bodner K, Calzavara A, Harrigan SP, Siddiqi A, Baral SD, Austin PC, Smylie J, Koh M, Sbihi H. (2024). [Social inequalities in COVID-19 deaths by area-level income: patterns over time and the mediating role of vaccination in a population of 11.2 million people in Ontario, Canada](https://www.medrxiv.org/content/10.1101/2024.01.15.24301331v1). medRxiv.
    - Wang S, Wang L, Baral SD, Moloney G, Johns J, Huber C, Mistry J, Khan K, Rao A, Janjua N, Williamson T. (2024). [Mobility changes following COVID-19 stay-at-home policies varied by socioeconomic measures: An observational study in Ontario, Canada](https://www.medrxiv.org/content/10.1101/2024.01.29.24301938v1). medRxiv. Also accepted by PLoS Global Health (In press).
    - Rucinski K, Knight J, Willis K, Wang L, Rao A, Roach MA, Phaswana-Mafuya R, Bao L, Thiam S, Arimi P, Mishra S. (2024). [Challenges and Opportunities in Big Data Science to Address Health Inequities and Focus the HIV Response](https://pubmed.ncbi.nlm.nih.gov/38916675/). Current HIV/AIDS Reports 21(4): 208-19.
    - Harrigan SP, Fibke CD, Velásquez García HA, Mak S, Wilton J, Prystajecky N, Tyson J, Wang L, Sander B, Baral S, Mishra S. (2024). [The mediating role of SARS-CoV-2 variants between income and hospitalisation due to COVID-19: A period-based mediation analysis](https://pubmed.ncbi.nlm.nih.gov/39117572/). American Journal of Epidemiology kwae266.
    - Xiu F, Flores Anato JL, Cox J, Grace D, Hart TA, Skakoon-Sparling S, Dvorakova M, Knight J, Wang L, Gatalo O, Campbell E. (2024). [Characteristics of the Sexual Networks of Men Who Have Sex With Men in Montréal, Toronto, and Vancouver: Insights from Canada’s 2022 Mpox Outbreak](https://academic.oup.com/jid/article-abstract/229/Supplement_2/S293/7602567?redirectedFrom=PDF). The Journal of Infectious Diseases 229(2): S293-304.
    - Wang L, Calzavara A, Baral S, Smylie J, Chan AK, Sander B, Austin PC, Kwong JC, Mishra S. (2023). [Differential patterns by area-level social determinants of health in Coronavirus Disease 2019 (COVID-19)-related mortality and non-COVID-19 mortality: a population-based study of 11.8 million people in Ontario, Canada](https://pubmed.ncbi.nlm.nih.gov/36303410/). Clin Infect Dis 76(6): 1110-1120.
    - Chen C, Baral S, Comins AC, Mcingana M, Wang L, Phetlhu RD, Mulumba N, Guddera V, Young K, Mishra S, Hausler H, Schwartz RS. (2022). [HIV- and sex work-related stigmas and quality of life of female sex workers living with HIV in South Africa: a cross-sectional study](https://bmcinfectdis.biomedcentral.com/articles/10.1186/s12879-022-07892-4). BMC Infect Dis 22: 910.
    - Wang L, Dowdy D, Comins C, Young K, Mcingana M, Muluba N, Mhlophe H, Chen C, Hausler H, Schwartz S, Baral S, Mishra S. (2022). [Health-related quality of life of female sex workers living with HIV in South Africa: a cross-sectional study with HIV in South Africa](https://onlinelibrary.wiley.com/doi/10.1002/jia2.25884). JIAS 25: e25884.
    - Mishra S, Silhol R, Knight J, Phaswanamafuya N, Diouf D, Wang L, Schwartz S, Boily MC, Baral S. (2021). [Estimating the epidemic consequences of HIV prevention gaps among key populations](https://onlinelibrary.wiley.com/doi/10.1002/jia2.25739). J Int AIDS Soc 24(S3): e25739.
    - Wang L, Moqueet N, Simkin A, Knight J, Ma H, Lachowsky NJ, Armstrong HL, Tan DHS, Burchell AN, Hart TA, Moore DM, Adam BD, MacFadden DR, Baral S, Mishra S. (2021). [Mathematical modelling of the influence of serosorting on the population-level HIV transmission impact of pre-exposure prophylaxis](https://journals.lww.com/aidsonline/Abstract/9000/Mathematical_modelling_of_the_influence_of.96503.aspx). AIDS 35(7): 1113-1125.
    - Wang L, Ma H, Yiu KCY, Calzavara A, Landsman D, Luong L, Chan AK, Kustra R, Kwong JC, Boily MC, Hwang S, Straus S, Baral SD, Mishra S. (2020). [Heterogeneity in testing, diagnosis and outcome in SARSCoV-2 infection across outbreak settings in the Greater Toronto Area, Canada: an observational study](http://cmajopen.ca/content/8/4/E627.full). CMAJ Open 8(4): E627-E636.
    - Mishra S, Wang L, Ma H, Yiu K, Paterson JM, Kim E, Schull MJ, Pequegnat V, Lee A, Ishiguro L, Coomes E, Chan A, Downing M, Landsman D, Straus S, Muller M. (2020). [Estimated surge in hospital and intensive care admission because of the coronavirus disease 2019 pandemic in the Greater Toronto Area, Canada: a mathematical modelling study](http://cmajopen.ca/content/8/3/E593.full). CMAJ Open 8(3): E593-E604.
    - Knight J, Baral S, Schwartz S, Wang L, Ma H, Young K, Hausler H, Mishra S. (2020). [Contribution of high risk groups’ unmet needs may be underestimated in epidemic models without risk turnover: a mechanistic modelling analysis](https://www.sciencedirect.com/science/article/pii/S2468042720300282). Infect Dis Model 5: 549-562.
    - Ma H, Wang L, Gichangi P, Mochache V, Manguro G, Musyoki HK, Bhattacharjee P, Cholette F, Sandstrom P, Becker ML, Mishra S. (2020). [Venue-based HIV testing at sex work hotspots to reach adolescent girls and young women living with HIV: a cross-sectional study in Mombasa, Kenya](https://journals.lww.com/jaids/Abstract/9000/Venue_based_HIV_testing_at_sex_work_hotspots_to.96194.aspx). J Acquir Immune Defic Syndr 84(5): 470-479.
    - Wang L, Tan DHS, Mishra S. (2020). [Evidence of non-random mixing by pre-exposure prophylaxis use among men who have sex with men partnerships in Melbourne, 2016 to 2018](https://journals.lww.com/jaids/Citation/9000/Letter_to_the_Editor__Evidence_of_non_random.96183.aspx). J Acquir Immune Defic Syndr 84(4): e22-23.
    - Wang L, Moqueet N, Lambert G, Grace D, Rodrigues R, Cox J, Lachowsky NJ, Noor SW, Armstrong HL, Tan DH, Burchell AN, Ma H, Apelian H, Knight J, Messier-Peet M, Jollimore J, Baral SD, Hart TA, Moore DM, Mishra S. (2019). [Population-level sexual mixing by HIV status and pre-exposure prophylaxis use among men who have sex with men in Montreal, Canada: Implications for HIV prevention](https://academic.oup.com/aje/advance-article/doi/10.1093/aje/kwz231/5587085). Am J Epidemiol 189(1): 44-54.
    `,
    linkedin: "https://www.linkedin.com/in/linwei-wang-90448494/",
    researchGate: "https://www.researchgate.net/profile/Linwei_Wang2/",
    googleScholar: "https://scholar.google.com/citations?user=ypTWJiIAAAAJ"
  },

  {
    id: "4",
    name: "Sharmistha Mishra",
    job_title: "Principal Investigator",
    image: "/images/team/sharmistha_mishra.png",
    role: "ResearchTeam" as Role,
    bio: `I am an infectious disease physician and mathematical modeler. I currently hold a Tier 2 [Canada Research Chair](http://www.chairs-chaires.gc.ca/) in Mathematical Modeling and Program Science.

    I grew up in Rourkela, Odisha (India) and then Sudbury, Ontario (Canada). I went to Laurentian University (BSc) and University of Toronto (MD, Internal Medicine Residency, Infectious Diseases Fellowship) and Imperial College London (MSc, Modern Epidemiology; PhD Mathematical Modeling).  In 2007, I did my clinical tropical medicine training at the Gorgas Course in Tropical Medicine. So I went to school for a long time and yup, I really like learning.

    I started on faculty at University of Toronto in Dec 2014 – and now I am working with a core team of amazing scientists and creative thinkers; with insightful fellows and clever students; and with terrific colleagues in several parts of the world. When I am not on clinical service, I spend a lot of time questioning and adapting my reasoning/logic, staring at results and figures, and debugging. And model checking. Writing. Reading. Writing. Teaching. Debugging. Between December 2014 and July 2015, I had an opportunity to work with the World Health Organization to support the Sierra Leone Ministry of Health and Sanitation during the 2014-2016 Ebola outbreak. The work spurred new partnerships and projects.
    
    My primary appointments:

    - Associate Professor, Department of Medicine, Division of Infectious Diseases, University of Toronto
    - [Clinician Scientist, Li Ka Shing Knowledge Institute, University of Toronto](http://stmichaelshospitalresearch.ca/researchers/sharmistha-mishra/)
    - [Scientist, MAP Centre for Urban Health Solutions, St. Michael’s Hospital of Unity Health Toronto](https://maphealth.ca/mishra/)

    Graduate trainee supervisory appointments:

    - [Institute of Medical Sciences](https://ims.utoronto.ca/faculty/faculty-online-community/faculty-members/mishraavsharmistha/)
    - [Institute of Health Policy, Management, and Evaluation, Dalla Lana School of Public Health](https://ihpme.utoronto.ca/faculty/sharmistha-mishra/)

    I was supported by:

    - University of Toronto Clinician Scientist Training Program (2008-2012)
    - British Commonwealth Scholarship (2008-2009)
    - Canadian Institute of Health Research Fellowship (2010-2015)
    - Canadian Institute of Health Research and Ontario HIV Treatment Network New Investigator (2015-2020)
    `,
    linkedin: "https://www.linkedin.com/in/sharmistha-mishra-4b814935/?originalSubdomain=ca/",
    orcid: "https://orcid.org/0000-0001-8492-5470",
    researchGate: "https://www.researchgate.net/profile/Sharmistha_Mishra2/",
    X: "https://twitter.com/mishrash?lang=en/"
  },

  {
    id: "5",
    name: "Chidumebi Idemili",
    job_title: "UofT PhD Student",
    image: "/images/team/chidumebi_idemili.jpg",
    role: "GradPostDoc" as Role,
    bio: "Chidumebi Idemili is a first-year PhD student in Health Systems Research with emphasis on Health Technology Assessment at the Institute of Health Policy, Management and Evaluation. She obtained a bachelor’s degree in Mathematics Education from the University of Nigeria, Nsukka, Nigeria, and a master’s degree in Applied Mathematical Sciences with Climate Change Modeling from Heriot-Watt University, Scotland. Chidumebi has an impressive research achievement that demonstrates her unwavering dedication to solving health challenges. Utilizing advanced modeling techniques, she worked on predicting blackfly habitats and investigated the impact of climate change on malaria spread in Nigeria. Her master’s dissertation on SARS-CoV-2 dynamics and ongoing PhD research on critical issues, such as HIV transmission and resource allocation efficiency, testify to her readiness for advanced scholarship and unwavering commitment to addressing global health challenges. Navigating essential subject areas in published articles centred on combatting anthrax outbreaks and assessing health system inefficiencies and epidemic preparedness, demonstrates her capacity to produce impactful research with real-world implications. Chidumebi’s trajectory reflects her exceptional methodological finesse, unparalleled theoretical understanding, and unwavering commitment to positively impacting the world through innovative research and evidence-based interventions.",
    linkedin: "https://www.linkedin.com/in/chidumebi-idemili-amima-578349182/"
  },

  {
    id: "6",
    name: "Nancy Tahmo",
    job_title: "UofT PhD Candidate",
    image: "/images/team/nancy_tahmo.jpg",
    role: "GradPostDoc" as Role,
    bio: `Nancy is a PhD Candidate in the Division of Epidemiology at Dalla Lana School of Public Health. She joined the Mishra Lab in 2023 as a trainee, where she is working with Dr. Sharmistha Mishra and collaborators in Kenya, assessing the influence of sexual networks on HIV epidemics among men who have sex with men. This project uses community-based participatory modeling to adapt an HIV transmission model and co-design a framework for scaling integrated community engagement in HIV prevention research.

    As a Disease Surveillance Specialist, Nancy previously led STI and HIV surveillance and prevention for Sarpy and Cass counties in Nebraska, U.S.A. Her previous work also included Global Health Security with One Health projects around emerging and re-emerging zoonotic diseases in Sub-Saharan Africa, like Ebola Virus Disease and Lassa Fever. She obtained a Master of Public Health in Epidemiology from the University of Nebraska Medical Center and a BSc. in Biochemistry from the University of Bamenda, Cameroon. Her research and work are value-driven and center on community relevance. She hopes to strengthen her expertise as an infectious disease epidemiologist and expand her skills in mathematical modeling to grow as a well-rounded leader in global community health.

    Nancy is an avid soccer player who enjoys cooking, singing, and dancing. She hopes to someday coach a professional soccer team.`,
    linkedin: "https://www.linkedin.com/in/nancy-tahmo-mph-04b1791b9/",
    googleScholar: "https://scholar.google.com/citations?hl=en&user=blEQK9AAAAAJ",
    status: "Finalizing Chapter 1 and developing modeling analyses for Chapters 2 and 3 of my thesis"
  },

  {
    id: "7",
    name: "Suzanne Shoush, MD",
    job_title: "MSc Candidate",
    image: "/images/team/suzanne_shoush.png",
    role: "GradPostDoc" as Role,
    bio: "I am completing my Master’s degree at the Institute of Health Policy, Management, and Evaluation at the University of Toronto, under the supervision of Sharmistha Mishra and [Janet Smylie](http://www.welllivinghouse.com/about-us/whos-involved/dr-janet-smylie/). My research looks at the transmission dynamics of infectious diseases through urban Indigenous communities. Key to our work is not just understanding how diseases spread, but also how interventions spread. For example: How does trust spread through a community? How does access to culturally safe resources impact the spread of a healthcare intervention through a community? My work explores kinship systems and re-envisioning the development of mathematical models of infectious disease transmission, using SARS-CoV-2 as an example.",
    linkedin: "https://www.linkedin.com/in/suzanne-shoush-23b255268/"
  },

  {
    id: "8",
    name: "Aastha Sharma",
    job_title: "Designer and Developer",
    image: "/images/team/aastha_sharma.jpg",
    role: "Trainee" as Role,
    bio: "Aastha Sharma is a fourth-year Computer Science student at the University of Toronto. As part of the UofT Work-Study Professional Experience Program, Aastha is the web designer and developer in the lab. With a passion for creating engaging and accessible digital experiences, Aastha is responsible for maintaining and enhancing the lab’s online presence – to help share our team’s work more broadly. She ensures the website stays up-to-date and is currently working to revamp the site’s design, giving it a refreshed, user-friendly look. Through her innovative design and development solutions, Aastha aims to make the new research conducted at the Mishra Lab more accessible and impactful to a broader audience. Outside of the lab, Aastha is actively engaged in coding [personal projects](https://www.aastha-sharma.com/), along with working on academic projects and exploring her creativity through painting. Aastha looks forward to contributing to the lab’s work and collaborating with the team!",
    linkedin: "https://www.linkedin.com/in/aastha-sharma-b5444821a/",
    github: "https://github.com/AasthaSharma272",
    status: "Coding with a hot cup of coffee"
  },

  {
    id: "9",
    name: "Ekta Mishra",
    job_title: "Summer Student",
    image: "/images/team/ekta_mishra.jpg",
    role: "Trainee" as Role,
    bio: "Ekta is an undergraduate student in the Arts and Science program at McMaster University. She has been on the team as a summer student since May 2022. Having academic interests that stretch from statistics and economics to film and political theory, Ekta is passionate about integrating areas of academic study to solve real-world problems. Particularly, Ekta cares about using evidence-based ideas to inform effective and innovative health policy. She hopes to help develop strategies that optimize resource and care allocation in resource-constrained areas. She is currently conducting a systematic review of HIV treatment cascade adherence in female sex workers in Sub-Saharan Africa. This work will better inform our understanding of the UN 90-90-90 goals, as they pertain to vulnerable and high-risk populations.",
    linkedin: "https://www.linkedin.com/in/ekta-mishra-4776741b5/"
  },

  {
    id: "10",
    name: "Min Xi",
    job_title: "Research Coordinator",
    image: "/images/team/min_xi.jpg",
    role: "Trainee" as Role,
    bio: `Min is a part-time research assistant with the lab. Min is also a PhD candidate at the University of Toronto, and is supported by a CIHR Doctoral Award. She is interested in studying how economic analyses and health technology assessment can help the implementation of new interventions in various populations. She is similarly interested in the translation of research into health policies to improve the quality of life of individuals. She started working with the team during her undergraduate studies in September 2018. Min is leading the following two research projects with the team:
    
    - A systematic review and meta-analysis of the HIV prevalence and the number of sexual partners of clients and non-paying male partners of female sex workers across countries in Sub-Saharan Africa
    - A systematic review of economic evaluations of HIV pre-exposure prophylaxis.

    She has presented her work from these two projects at the International AIDS Conference and her work has informed the UNAIDS Reference Group on HIV Estimation and Modeling. Min is currently writing up the papers from these two projects as the lead author.

    In 2021, Min joined the Ottawa Health Research Institute as a part-time research assistant with [Dr. Kednapa Thavorn](http://www.ohri.ca/profile/kthavorn), [Dr. Alice Zwerling](https://med.uottawa.ca/epidemiology/people/zwerling-alice), and Dr. Mishra to lead another two studies with our team:
    
    - Characterizing the temporal and population-specific pattern of the health system costs related to HIV in Ontario, using health-administrative data and the Ontario Cohort Study.
    - Estimating the attributable costs of HIV in Ontario, using health-administrative data and the Ontario Cohort Study.

    The findings from these two costing studies will help inform the implementation and scale-up of HIV prevention and care services, as well as provide updated cost data for use in economic evaluations of HIV interventions in Ontario and Canada.   
    `,
    linkedin: "https://www.linkedin.com/in/min-xi-496716139/",
    researchGate: "https://www.researchgate.net/profile/Min-Xi",
    orcid: "https://orcid.org/0000-0002-8398-7239"
  },
];